<?php
$this->title = "internal dashboard prototype";
$this->headTitle($this->title);
?>
<div style="margin-left:190px;">

<br>
<br>
<form  action="<?php echo $this->url(array('controller'=>'issue','action'=>'index'));?>">
    <input id="choice" type="submit" value="Jira Issues">
</form>

<br>
<br>
<br>
<form  action="<?php echo $this->url(array('controller'=>'support','action'=>'index'));?>">
    <input id="choice" type="submit" value="Zendesk Issues">
</form>
<br>
<br>
<br>

<form action="<?php echo $this->url(array('controller'=>'instance','action'=>'index'));?>">
    <input id="choice" type="submit" value="Instance Activity">
</form>
<br>
<br>
<br>
</div>
