<?php
$this->title = "internal dashboard prototype";
$this->headTitle($this->title);
?>
<p>
<a href="<?php echo $this->url(array('controller'=>'graph','action'=>'index'));?>">Customers Activity</a>
<br>
<br>
<br>
<a href="<?php echo $this->url(array('controller'=>'mongo','action'=>'index'));?>">Mongo Stats</a>
<br>
<br>
<br>
<a href="<?php echo $this->url(array('controller'=>'index','action'=>'list'));?>">Bluekiwi Directory</a>
</p>
