<?php
$this->title = "Zendesk page";
$this->headTitle($this->title);
?>
<div  style="float:left; width :170px; ">
    <tr>
      <?php echo $this->form.'<br/>'; ?>
    </tr>
</div>
<div style="margin-left:190px;">
<table>
  <tr>
    <div id="container" style="width:50%; height:300px;"/>
  </tr>
  <tr>
      <div id="container2" style="width:50%; height:300px;"/>
  </tr>
</table>
</div>
<script>
$(function () {
    $('#container').highcharts({
            chart: {
            type: 'line'
        },
        title: {
            text: 'Ticket status by creation date'
        },
        xAxis: {
            type: 'category'
            },
        yAxis: {
            min: 0
            },
      series: [
      {name : 'open', data: <?php echo $this->open; ?>},
      {name : 'solved', data: <?php echo $this->solved; ?>},
      {name : 'pending', data: <?php echo $this->pending; ?>}
      ]
  });
});
$(function () {
    $('#container2').highcharts({
            chart: {
            type: 'column'
        },
        title: {
            text: 'Ticket priority by creation date'
        },
        xAxis: {
            type: 'category'
            },
        yAxis: {
            min: 0
            },
      series: [
      {name : 'urgent', data: <?php echo $this->urgent; ?>},
      {name : 'high', data: <?php echo $this->high; ?>},
      {name : 'normal', data: <?php echo $this->normal; ?>}
      ]
  });
});
</script>
