<?php
$this->title = "Zendesk page";
$this->headTitle($this->title);
?>
<table>
  <tr><h2>all tickets</h2>
  </tr>
  <tr>
    <div id="container" style="width:50%; height:300px;">
    </div>
  </tr>
  <tr><h2>recent ticket</h2>
  </tr>
</table>
<script>
$(function () {
    $('#container').highcharts({
            chart: {
            type: 'line'
        },
        title: {
            text: 'Tickets Number'
        },
        xAxis: {
            type: 'category'
            },
        yAxis: {
            min: 0
            },
      series: [
      {name : 'open', data: <?php echo $this->open; ?>},
      {name : 'solved', data: <?php echo $this->solved; ?>},
      {name : 'pending', data: <?php echo $this->pending; ?>}
      ]
  });
});
</script>