<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('this is layout');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
    <?php echo $this->HeadMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
    <script src="js/jquery.min.js"></script>
    <script src="js/highcharts.js"></script>
</head>
<body>
    <div id="content">
        <h1><?php echo $this->escape($this->title); ?></h1>
        <?php echo $this->layout()->content; ?>
    </div>
<!--    <div id="sidebar">-->
<!--        <?php echo $this->layout()->sidebar; ?>-->
    <!--</div>-->
    <div id="containerUp"  style="width:50%; height:300px;"></div>
    <div id="containerDown" style="width:50%; height:300px;"></div>
</body>
</html>
