<?php
$this->title = "Instance page";
$this->headTitle($this->title);
?>
<div  style="float:left; width :170px; ">
    <tr>
      <?php echo $this->form.'<br/>'; ?>
    </tr>
</div>
<div style="margin-left:190px;">
<table>
  <tr>
    <div id="container" style="width:50%; height:300px;"/>
  </tr>
</table>
</div>
<script>
$(function () {
    $('#container').highcharts({
            chart: {
            type: 'line'
        },
        title: {
            text: 'Instance Statistics by date'
        },
        xAxis: {
            type: 'category'
            },
        yAxis: {
            min: 0
            },
      series: [
      {name : 'space', data: <?php echo $this->space; ?>},
      {name : 'user', data: <?php echo $this->user; ?>},
      {name : 'private', data: <?php echo $this->private; ?>}
      ]
  });
});
</script>
