<?php
$this->title = 'Number of request since 15 mn';
$this->headTitle($this->title);
?>
<p>

<script language="Javascript">
      function verifierSaisie() {
              if(document.authentification.login.value=="") {
                  alert("Login non saisi.");
          }
          else {
              if(document.authentification.pass.value=="") {
                  alert("Pass non saisi");
          }
          else {
              document.authentification.cours.value="en cours...";
              document.authentification.submit();
          }
        }
      }
</script>
<div align="center">
  <form name="authentification" action="<?php $PHP_SELF ?>" method="post">
    <table width="90%" border="0" cellspacing="0" >
      <tr>
        <td colspan="2" align="center"><b><font size="+1">Authentification</font></b></td>
      </tr>
      <tr>
        <td>Login :</td>
        <td><input style="border-style:solid" type="text" name="login" size="16" maxlength="30"></td>
      </tr>
      <tr>
          <td>Pass :</td>
          <td><input style="border-style:solid" type="password" name="pass" size="16" maxlength="30"></td>
      </tr>
      <tr>
          <td colspan="2" align="center"><input type="hidden" value="true" name="saisieEffectuer">
          <input type="button" value="Annuler" onclick="window.close()">&nbsp;
          <input type="button" OnClick="verifierSaisie()" value="Ok"></td>
      </tr>
    </table>
        <input type='text' style='border:none; ' name='cours' value='' size=11 >
  </form>
</div>
