<?php
$this->title = "Jira page";
$this->headTitle($this->title);
?>
<div  style="float:left; width :170px; ">
  <table>
    <tr>
      <?php echo $this->form.'<br/>'; ?>
    </tr>
    <tr>
<?php
echo 'projects'.'<br/>';
foreach($this->currentitems as $item )
    echo $item[1].'<br/>';
                         ?>
    </tr>
  </table>
</div>
<div style="margin-left:190px;">
  <table>
    <tr>  <td>
        <div id="container"  style="height:300px;"/>          </td>
    </tr>
    <tr>  <td>
        <div id="container2" style="height:300px;"/>          </td>
    </tr>
  </table>
</div>
<script>
$(function () {
    $('#container').highcharts({
            chart: {
            type: 'line'
        },
        title: {
            text: 'Ticket status by creation date'
        },
        xAxis: {
            type: 'category'
            },
        yAxis: {
            min: 0
            },
      series: [
      {name : 'open', data: <?php echo $this->open; ?>},
      {name : 'resolved', data: <?php echo $this->resolved; ?>},
      {name : 'closed', data: <?php echo $this->closed; ?>}
      ]
  });
});
$(function () {
    $('#container2').highcharts({
            chart: {
            type: 'column'
        },
        title: {
            text: 'Ticket priority by creation date'
        },
        xAxis: {
            type: 'category'
            },
        yAxis: {
            min: 0
            },
      series: [
      {name : 'P0', data: <?php echo $this->p0; ?>},
      {name : 'P1', data: <?php echo $this->p1; ?>},
      {name : 'P2', data: <?php echo $this->p2; ?>}
      ]
  });
});
</script>
