<?php
$this->title = "customer stats";
$this->headTitle($this->title);
?>
<div  style="float:left; width :150px; ">
  <table>
    <tr>
      <?php echo $this->form.'<br/>'; ?>
    </tr>
    <tr>
<?php
echo 'Instance Active_Mbr'.'<br/>';
foreach($this->currentitems as $item )
    echo $item[0].' '.$item[1].'<br/>';
             ?>
    </tr>
  </table>
</div>
<div style="margin-left:170px;">
  <table>
    <tr>  <td>
        <div id="containerUp"  style="width:40%; height:300px;">
        </div>  </td>  <td>
        <div id="containerUpLeft"  style="width:40%; height:300px;">
        </div>  </td>
    </tr>
    <tr>  <td>
        <div id="containerDown" style="width:40%; height:300px;">
        </div>  </td>  <td>
        <div id="containerDownLeft"  style="width:40%; height:300px;">
        </div>       </td>
    </tr>
  </table>
</div>
<script>
$(function () {
    $('#containerUp').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: '<?php echo $this->instance.' Active Members' ?>'
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -60,
                style: {
                    fontSize: '9px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        },
        yAxis: {    min:0
        },
        legend: {
        },
        series: [{
            name: 'requests',
            data: <?php echo $this->items ?>
        }
        ]
    });
});
function chartbis(datachart){
  var datatab=jQuery.parseJSON(datachart);
$('#containerDownLeft').highcharts({
    chart: {
        type: 'line'
    },
    title: {
        text: '<?php echo $this->instance.' like activity'  ?>'
    },
    xAxis: {
    type: 'category'
    },
    yAxis: {
    min:0
    },
    series: [{
            name: 'requests',
            data: datatab
        }
        ]
});
}
$(document).ready(function(){
    $.post('mongo/jsget',
           {'message' : '<?php echo $this->instance ?>'},
            function (data) {
              chartbis(data);
          }
   );
});
function chartter(datachart){
  var datatab=jQuery.parseJSON(datachart);
$('#containerUpLeft').highcharts({
    chart: {
        type: 'line'
    },
    title: {
        text: '<?php echo $this->instance.' Publish activity' ?>'
    },
    xAxis: {
    type: 'category'
    },
    yAxis: {
    min:0
    },
    series: [{
            name: 'requests',
            data: datatab
        }
        ]
});
}
$(document).ready(function(){
    $.post('mongo/jsgetpost',
    {'message' : '<?php echo $this->instance ?>'},
            function (data) {
              chartter(data);
          }
   );
});
</script>