<?php
$this->title = "customer stats";
$this->headTitle($this->title);
?>
<table>               
<tr>
  <?php echo $this->form ?>
</tr>   
<?php
foreach($this->currentitems as $item ) 
    echo '<tr><td>'.$item[0].'</td><td>'.$item[1].'</td></tr>';
?>
</table>               
<table>               
  <tr>  <td>                               
      <div id="containerUp"  style="width:50%; height:300px;">                           
      </div>  </td>  <td>                               
      <div id="containerUpLeft"  style="width:50%; height:300px;">                           
      </div>  </td>             
  </tr>             
  <tr>  <td>                               
      <div id="containerDown" style="width:50%; height:300px;">                           
      </div>  </td>  <td>            
      <div>                           
</div>
       </td>             
  </tr>
</table>

<script>
$(function () { 
    $('#containerUp').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: '<?php echo $this->instance.' Active Members' ?>'
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -60,
                style: {
                    fontSize: '9px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        },
        yAxis: {    min:0
        },
        legend: {
        },
        series: [{
            name: 'requests',
            data: <?php echo $this->items ?> 
        }
        ]
    });
});
function chartbis(datachart){
  var datatab=jQuery.parseJSON(datachart);
$('#containerDown').highcharts({
    chart: {
        type: 'line'
    },
    title: {
        text: '<?php echo $this->instance.' like activity'  ?>'
    },
    xAxis: {
    type: 'category'
    },
    yAxis: {
    min:0
    },
    series: [{
            name: 'requests',
            data: datatab
        }
        ]
});         
}
$(document).ready(function(){
    $.post('mongo/jsget',
           {'message' : '<?php echo $this->instance ?>'},
            function (data) {
              chartbis(data);
          }
   );
});
function chartter(datachart){
  var datatab=jQuery.parseJSON(datachart);
$('#containerUpLeft').highcharts({
    chart: {
        type: 'line'
    },
    title: {
        text: '<?php echo $this->instance.' Publish activity' ?>'
    },
    xAxis: {
    type: 'category'
    },
    yAxis: {
    min:0
    },
    series: [{
            name: 'requests',
            data: datatab
        }
        ]
});         
}
$(document).ready(function(){
    $.post('mongo/jsgetpost',
    {'message' : '<?php echo $this->instance ?>'},
            function (data) {
              chartter(data);
          }
   );
});
</script>