
__________________________________________
/*    $.ajax({
          url : 'mongo/jsget',
          type : 'GET',
          async : true,
          dataType: "json",
          succcess : function (data) {
            chartdown(data);
          }
    });*/
    
    
    ___________________________________
function toto(datachart){
            $(".show-msg").html(datachart);
$('#containerUp').highcharts({
    chart: {
        type: 'line'
    },
    title: {
        text: 'Publish activity'
    },
    xAxis: {
    categories: ['Apples', 'Bananas', 'Oranges']
    },
    yAxis: {
    },
    series: [{
        name : 'serie_z',
        data : [datachart]
    }]
});         
}
$(document).ready(function(){

    $.ajax({
          url : 'mongo/jsget',
          type : 'GET',
          async: true,
          success : function (data) {
            toto(data);
          }
   });

});